//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewResourceManager {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewResourceManager.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   확장 프로그램 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddExtensionButton {
            get {
                return ResourceManager.GetString("AddExtensionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장 프로그램을 제거하였습니다. 다시 통합하려면 확장 프로그램 추가 버튼을 누르십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EjectMessage {
            get {
                return ResourceManager.GetString("EjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내보내기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장 프로그램에 추가/제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExtensionButton {
            get {
                return ResourceManager.GetString("ExtensionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Resource Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Form1Title {
            get {
                return ResourceManager.GetString("Form1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Form2CloseButton {
            get {
                return ResourceManager.GetString("Form2CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Form2Title {
            get {
                return ResourceManager.GetString("Form2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   가져오기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportEditorCancelButton {
            get {
                return ResourceManager.GetString("ImportEditorCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportEditorOkButton {
            get {
                return ResourceManager.GetString("ImportEditorOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImportEditorTitle {
            get {
                return ResourceManager.GetString("ImportEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   안내과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InformationMsg {
            get {
                return ResourceManager.GetString("InformationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게임 프로젝트 파일을 선택해주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenFileDialog2Title {
            get {
                return ResourceManager.GetString("OpenFileDialog2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게임 프로젝트 파일이 아닌 다른 파일을 선택하였습니다. 다시 선택해주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenMvGameFolderMessageBox {
            get {
                return ResourceManager.GetString("OpenMvGameFolderMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   미리보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PreviewButton {
            get {
                return ResourceManager.GetString("PreviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장 프로그램 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveExtensionButton {
            get {
                return ResourceManager.GetString("RemoveExtensionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 경로가 잘못돼 오류가 발생하였습니다 (경로에 공백이 포함되어있다면 반드시 제거하십시오)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveSpaceIntoPath {
            get {
                return ResourceManager.GetString("RemoveSpaceIntoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   투명도 설정을 위한 리소스 관리자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RMMV_ExtensionSchema_hint {
            get {
                return ResourceManager.GetString("RMMV_ExtensionSchema_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Resource Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RMMV_ExtensionSchema_name {
            get {
                return ResourceManager.GetString("RMMV_ExtensionSchema_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비트맵 이미지 (.bmp)|*.bmp|JPEG 이미지 (.jpeg)|*.jpeg|Png 이미지 (.png)|*.png과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveFileDialog1Filter {
            get {
                return ResourceManager.GetString("SaveFileDialog1Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   투명색 (왼쪽 클릭) :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TransparentLabel {
            get {
                return ResourceManager.GetString("TransparentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   투명색 설정 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TransperantPanel {
            get {
                return ResourceManager.GetString("TransperantPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 추가된 투명도 데이터를 삭제할 수 있습니다. Delete 키를 누르거나 삭제 버튼을 누르십시오. 투명색 데이터 추가는 가져오기 버튼을 이용하십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TransperantPanelTooltip {
            get {
                return ResourceManager.GetString("TransperantPanelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 확장 프로그램이 추가되어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateRegistryAlreadyProgram {
            get {
                return ResourceManager.GetString("UpdateRegistryAlreadyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장 프로그램을 툴에서 제거할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateRegistryDeleteProgram {
            get {
                return ResourceManager.GetString("UpdateRegistryDeleteProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확장 프로그램을 추가하였습니다. RPG Maker MV를 재실행해주십시오.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UpdateRegistryRetryProgramMsg {
            get {
                return ResourceManager.GetString("UpdateRegistryRetryProgramMsg", resourceCulture);
            }
        }
    }
}
